### ISSUE TITLE
Unable to automatically install with Terraform 0.13

### ISSUE THREAD

**Issue by bramd** [aequitas/terraform-provider-transip#34]
I have added the provider to my Terraform configuration:

```
terraform {
  required_providers {
    transip = {
      source  = "aequitas/transip"
      version = "0.1.6"
    }
  }
}
```

When running terraform init, I get the following:

```
Error while installing aequitas/transip v0.1.6: could not query provider
registry for registry.terraform.io/aequitas/transip: failed to retrieve
authentication checksums for provider: 404 Not Found
```

**Comment by aequitas** [comment]
I’ll get back on this next week as I’m currently on holiday. For now try if
a lower version works.

Op ma 17 aug. 2020 om 12:46 schreef Bram Duvigneau <notifications@github.com

**Comment by bramd** [comment]
Thanks, I fixed it for now by putting the binary in the .terraform 
directory manually.

**Comment by angelosleebos** [comment]
@bramd Hello Bram,

Can you please explain your workaround?

**Comment by aequitas** [comment]
It’s in the readme
https://github.com/aequitas/terraform-provider-transip#terraform-012

Op do 20 aug. 2020 om 16:14 schreef angelosleebos <notifications@github.com>

**Comment by angelosleebos** [comment]
Ah right, i knew i did that already. 

i am still getting an error. 

Error: Failed to install provider

Error while installing hashicorp/transip: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/transip

**Comment by bramd** [comment]
The plugin directory structure has changed in Terraform 0.13. Put your 
plugins in `.terraform` in your project folder. Not at my computer right 
now, but see the Terraform docs for details. Structure should be 
something like 
`.terraform/registry.terraform.io/vendor/plugin/version/arch`.

**Comment by aequitas** [comment]
Should be fixed now in v0.1.7. I used the GoReleaser to release this version. Don't know yet why it didn't work with the manual  released one, will investigate.
